# Generated by Django 2.1.7 on 2019-02-28 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nascimento', models.DateField()),
                ('nacionalidade', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('lancamento', models.DateField()),
                ('descricao', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='genero',
            name='livro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='biblioteca.Livro'),
        ),
        migrations.AddField(
            model_name='editora',
            name='livro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='biblioteca.Livro'),
        ),
        migrations.AddField(
            model_name='autor',
            name='livro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='biblioteca.Livro'),
        ),
    ]
