# Generated by Django 2.1.7 on 2019-02-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='livro',
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
