# Generated by Django 2.1.7 on 2019-02-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20190228_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='livro',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
